name = "gemini-balance"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "gemini-balance"
database_id = "71b0b17d-2f0c-4d99-b3a2-a8024deaea35"  # 需要替换为实际的数据库ID

# KV 存储绑定 (用于缓存和速率限制)
[[kv_namespaces]]
binding = "KV"
id = "951dd8f44fa346a7a7da3a4859e4e6d0"

# 开发环境配置
[env.dev]
name = "gemini-balance-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "gemini-balance-dev"
database_id = "71b0b17d-2f0c-4d99-b3a2-a8024deaea35"

[[env.dev.kv_namespaces]]
binding = "KV"
id = "951dd8f44fa346a7a7da3a4859e4e6d0"

# 生产环境配置
[env.production]
name = "gemini-balance"

[[env.production.d1_databases]]
binding = "DB"
database_name = "gemini-balance"
database_id = "71b0b17d-2f0c-4d99-b3a2-a8024deaea35"

[[env.production.kv_namespaces]]
binding = "KV"
id = "951dd8f44fa346a7a7da3a4859e4e6d0"
